### ISSUE TITLE
Captive Signing doesn't load on iOS 16.0

### ISSUE THREAD

**Issue by ajrotert** [docusign/native-ios-sdk#166]
**Issue:** Captive Signing doesn't finish loading on iOS 16.0

```swift
        guard let viewController = UIApplication.shared.activeWindow?.rootViewController?.topPresentedViewController() else { return .failed }

        DSMEnvelopesManager().presentCaptiveSigning(
            withPresenting: viewController,
            signingUrl: signingUrl.absoluteString,
            envelopeId: envelopeId,
            recipientId: nil,
            animated: true
        )
```

### Reproduce: 
Call `presentCaptiveSigning` on an iOS 16.0 simulator or device. 

### Screenshot: 
![image](https://github.com/docusign/native-ios-sdk/assets/44625749/d41974ad-78ab-4c4a-aaf7-26faa1cdd685)

### Video: 

https://github.com/docusign/native-ios-sdk/assets/44625749/55460350-72a3-4689-93b1-5eb9f5e598af

### Expected: 
**Video on iOS 17**

https://github.com/docusign/native-ios-sdk/assets/44625749/f553249b-317c-452b-8ce5-ad46f517bb7f

**Comment by esilva600** [comment]
Hello,

The article below shows a walkthorugh on how to perform Embedded Signing on iOS:
https://www.docusign.com/blog/developers/embedded-signing-the-native-ios-sdk

If further assistance is needed, you need to log a ticket and reach out to the DocuSign Mobile Integrations Team

**Comment by ajrotert** [comment]
> Hello,
> 
> The article below shows a walkthrough on how to perform Embedded Signing on iOS: https://www.docusign.com/blog/developers/embedded-signing-the-native-ios-sdk
> 
> If further assistance is needed, you need to log a ticket and reach out to the DocuSign Mobile Integrations Team

Where can I reach out to the `DocuSign Mobile Integrations Team`? I believe that this is an issue with the SDK, as it works on iOS17, but doesn't on iOS16. 

Thanks

**Comment by ashokds** [comment]
Hi @ajrotert & @esilva600 :

Thanks for adding the details on this issue. 

Will investigate the issue and post update here.

**Comment by ashokds** [comment]
Hi @ajrotert : 

Could you try again on iOS16 simulator as there was a known issue that obstructed the Embedded Signing to finish loading on iOS 16 and earlier. It's been resolved since then. 

Thanks!

**Comment by ashokds** [comment]
Closing this as underlying incident was fixed.

**Comment by jonathansds** [comment]
It's still happening for me.
The initial screen even loads behind but the loading spinner is not dismissed. I am testing on iOS 17.5
![Uploading Simulator Screenshot - iPhone 15 Pro - 2024-09-06 at 10.15.03.png…]()

**Comment by mmohareb** [comment]
Hello @jonathansds 
I think this is a different issue, can you open a new issue with more details about how you are starting the signing session and maybe a code snippet with a recording of the whole flow, to make it possible for us to investigate?

**Comment by jonathansds** [comment]
I still believe it's the same issue but in any case, I created a new issue here: https://github.com/docusign/native-ios-sdk/issues/171
