### ISSUE TITLE
ITMS-90809: Deprecated API Usage - UIWebView

### ISSUE THREAD

**Issue by jrodriguez-tera** [docusign/native-ios-sdk#26]
Hello everybody, I hope you're doing well.

I have the following problem, we are planning to release a new app around May 2020 and during our beta testing .we are receiving the following warning from Apple everytime we upload a new build to TestFlight

**ITMS-90809: Deprecated API Usage** - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information. 

Our project doesn't use UIWebViews and our other third-party libraries are up to date and don't use it neither. I have reviewed our build packages and performed an `grep -r "UIWebView" .` getting following outcome:

<img width="1025" alt="DocuSign" src="https://user-images.githubusercontent.com/40605460/77196792-0ba05000-6ab2-11ea-8427-9c4e61a9bf20.png">

Do you have an estimate on when are you expecting to migrate those clases to WKWebView? Otherwise, new developers that would like to use your native sdk for iOS in their apps won't be able to submit versions to the App Store.

Thanks in advance for your attention.

Docusign SDK Version : 2.2.3
Docusign SDK source url : https://github.com/docusign/native-ios-sdk

**Comment by thomas-dang** [comment]
Hi @jrodriguez-tera,

We have released version 2.2.4 of our SDK, which includes the change from UIWebView to WKWebView. Please give that version a try.

Thanks.

**Comment by jrodriguez-tera** [comment]
Hi @thomas-dang , those are good news, I will try it and will let you know how our tests went. Thanks

**Comment by jrodriguez-tera** [comment]
Hi @thomas-dang,

I've updated to version 2.2.4, there are a couple of changes that are still missing in the migration. Here's what I've found:

<img width="1051" alt="DocuSign2 2 4" src="https://user-images.githubusercontent.com/40605460/77931489-d940e080-7271-11ea-9ef2-cc8acc6f8778.png">

In case you can't see the image, here are the remaining two cases where an instance or use of UIWebView was found:

> Binary file ./Frameworks/DocuSignSDK.framework/DSMSettingsWebViewController.storyboardc/Xoo-VJ-0hw-view-cLu-6v-cm9.nib/objects-13.0+.nib matches
> Binary file ./Frameworks/DocuSignSDK.framework/DSMSettingsWebViewController.storyboardc/Xoo-VJ-0hw-view-cLu-6v-cm9.nib/runtime.nib matches
> 

Thanks again for your help guys.

**Comment by thomas-dang** [comment]
Hi @jrodriguez-tera,

Thank you for the heads up. We will take a look, and get back to you.

Thanks.

**Comment by jrodriguez-tera** [comment]
Hi @thomas-dang ,

I'm sorry to bother you but, do you guys have any updates about this?

**Comment by thomas-dang** [comment]
Hi @jrodriguez-tera,

Thanks for following up. We have released version 2.2.5 of our SDK to migrate the remaining UIWebView instances to WKWebView. Would you mind upgrading to this latest version of our SDK?

Thanks.

**Comment by jrodriguez-tera** [comment]
Hi @thomas-dang ,

Thanks for the update, this is finally fixed in the SDK version 2.2.5.

**Comment by thomas-dang** [comment]
Great, thank you @jrodriguez-tera.
